# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.4
    hooks:
    -   id: clang-format -i
        args:
        - "-style=file:developer-tools/.clang-format"
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    -   id: gitlint
        args:
        - "--config developer-tools/.gitlint"
-   repo: https://git.gitlab.arm.com/iot/open-iot-sdk/tools/developer-tools.git
    rev: b07ccfd40f6aebcce0464c1bc140dc9c0b47fa06
    hooks:
    -   id: banned-api
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: # arguments to configure flake8
        # making line length compatible with black
        - "--max-line-length=88"
